// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/laushunyu/pmp/internal/dao/internal"
)

// internalTaskRecordDao is internal type for wrapping internal DAO implements.
type internalTaskRecordDao = *internal.TaskRecordDao

// taskRecordDao is the data access object for table task_record.
// You can define custom methods on it to extend its functionality as you wish.
type taskRecordDao struct {
	internalTaskRecordDao
}

var (
	// TaskRecord is globally public accessible object for table task_record operations.
	TaskRecord = taskRecordDao{
		internal.NewTaskRecordDao(),
	}
)

// Fill with you ideas below.
