// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/laushunyu/pmp/internal/dao/internal"
)

// internalWorkerDao is internal type for wrapping internal DAO implements.
type internalWorkerDao = *internal.WorkerDao

// workerDao is the data access object for table worker.
// You can define custom methods on it to extend its functionality as you wish.
type workerDao struct {
	internalWorkerDao
}

var (
	// Worker is globally public accessible object for table worker operations.
	Worker = workerDao{
		internal.NewWorkerDao(),
	}
)

// Fill with you ideas below.
